from .elephant import Elephant
from .giraffe import Giraffe
from .kangaroo import Kangaroo
from .koala import Koala
from .lion import Lion
from .llama import Llama
from .panda import Panda
from .tiger import Tiger
from .zebra import Zebra
